version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: filmzone-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: filmzone
    volumes:
      - mongodb_data:/data/db
      - ./backend/scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - filmzone-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: filmzone-backend
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: development
      MONGO_URI: mongodb://admin:password123@mongodb:27017/filmzone?authSource=admin
      JWT_SECRET: your-super-secret-jwt-key-change-this-in-production
      PORT: 4000
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - filmzone-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: filmzone-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:4000/api
      REACT_APP_CLOUDINARY_CLOUD_NAME: your-cloudinary-cloud-name
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - filmzone-network

volumes:
  mongodb_data:

networks:
  filmzone-network:
    driver: bridge
