services:
  - type: web
    name: filmzone-frontend
    env: static
    rootDir: frontend
    nodeVersion: 18
    buildCommand: npm ci && npm run build
    staticPublishPath: ./build
    pullRequestPreviewsEnabled: false
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=31536000
      - path: /filmzonelogo.png
        name: Cache-Control
        value: public, max-age=31536000
    envVars:
      - key: VITE_API_URL
        value: https://filmzone-backend.onrender.com/api
      - key: VITE_CLOUDINARY_CLOUD_NAME
        value: your-cloudinary-cloud-name
      - key: NODE_ENV
        value: production

  - type: web
    name: filmzone-backend
    env: node
    rootDir: backend
    buildCommand: npm ci
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        value: mongodb+srv://username:password@cluster.mongodb.net/filmzone
      - key: JWT_SECRET
        value: your-super-secret-jwt-key-change-this-in-production
      - key: PORT
        value: 4000
      - key: CLOUDINARY_CLOUD_NAME
        value: your-cloudinary-cloud-name
      - key: CLOUDINARY_API_KEY
        value: your-cloudinary-api-key
      - key: CLOUDINARY_API_SECRET
        value: your-cloudinary-api-secret
